### ISSUE TITLE
Fermenter thinks it's a Greydwarf!

### ISSUE THREAD

**Issue by Karmacopper** [LTmadness/FermenterPercentage#2]
After the latest Valheim update, this is happening:

![eD6ysudVtA](https://user-images.githubusercontent.com/7628623/225708725-418c0d99-06a1-497c-8334-9c863399e3ef.jpg)

**Comment by LTmadness** [comment]
will look into it this weekend

**Comment by LTmadness** [comment]
Could you get in touch with me on my discord: ***** ? would be a huge help

**Comment by Karmacopper** [comment]
Sent you a friend DM
