### ISSUE TITLE
Inquiry

### ISSUE THREAD

**Issue by ValhallaCommunity** [LTmadness/FermenterPercentage#3]
Hey LT,

Can this mod be client side only? (ie only have to greylist on server)

Thank you

**Comment by LTmadness** [comment]
Hey,

This mod is client side only

**Comment by LTmadness** [comment]
Have released improved version of this mod under new name: https://valheim.thunderstore.io/package/LTmadness/GumshoeTimerSuite

**Comment by ValhallaCommunity** [comment]
Thanks LT!! This is great to know!
